### ISSUE TITLE
Cannot save map due to durability QoS in humble

### ISSUE THREAD

**Issue by TZECHIN6** [Project-MANAS/slam_gmapping#11]
After complete the online slam, I run ros2 run nav_map_saver map_saver_cli -f myMap.

And the error is what is stated in title, fail to spin map subscription, and map message can not send due Durability QoS from map_saver node

**Comment by YisrealHung** [comment]
Because of the QoS mismatch problem
Just replace the code in slam_gmapping/src/slam_gmapping.cpp with transient_local.
// sst_ = this->create_publisher<nav_msgs::msg::OccupancyGrid>("map", rclcpp::SystemDefaultsQoS());
sst_ = this->create_publisher<nav_msgs::msg::OccupancyGrid>("map", rclcpp::QoS(10).reliable().transient_local());

**Comment by TZECHIN6** [comment]
Yes you are right. I figure it out at that day night, sorry not remember to close the issue. btw thanks for your sharing.
